/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_32 (
    input [5:0] opcode,
    input [15:0] a,
    input [15:0] b,
    output reg zero,
    output reg ver,
    output reg neg,
    output reg [15:0] outsum,
    output reg overflow
  );
  
  
  
  reg [16:0] actualsum;
  
  reg [15:0] negative;
  
  always @* begin
    negative = a - b;
    
    case (opcode[0+1-:2])
      2'h0: begin
        actualsum = a + b;
      end
      2'h1: begin
        actualsum = a - b;
      end
      2'h2: begin
        actualsum = a * b;
      end
      2'h3: begin
        actualsum = a - ((a / b) * b);
      end
      default: begin
        actualsum = a + b;
      end
    endcase
    outsum = actualsum[0+15-:16];
    ver = (a[15+0-:1] & ~b[15+0-:1] & (~negative[15+0-:1])) | ((~a[15+0-:1]) & (b[15+0-:1]) & negative[15+0-:1]);
    zero = (~|negative);
    neg = actualsum[16+0-:1];
    overflow = (a[15+0-:1] & b[15+0-:1] & (~actualsum[15+0-:1])) | ((~a[15+0-:1]) & (~b[15+0-:1]) & actualsum[15+0-:1]);
  end
endmodule
