/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module bitshift_34 (
    input [5:0] opcode,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] z
  );
  
  
  
  always @* begin
    
    case (opcode[0+1-:2])
      2'h0: begin
        z = a << b[0+3-:4];
      end
      2'h1: begin
        z = a >> b[0+3-:4];
      end
      2'h3: begin
        z = $signed(a) >>> b[0+3-:4];
      end
      2'h2: begin
        z = $signed(a) <<< b[0+3-:4];
      end
      default: begin
        z = a;
      end
    endcase
  end
endmodule
