/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     ROW = ROW
     COL = COL
*/
module led_manager_29 (
    input clk,
    input rst,
    input [9:0] leftstack,
    input [9:0] middlestack,
    input [9:0] rightstack,
    output reg [19:0] led_output0,
    output reg [19:0] led_output1,
    output reg [19:0] led_output2
  );
  
  localparam ROW = 4'ha;
  localparam COL = 1'h1;
  
  
  always @* begin
    led_output0[0+0+1+0-:1] = leftstack[0+0-:1];
    led_output0[2+0+1+0-:1] = leftstack[1+0-:1];
    led_output0[4+0+1+0-:1] = leftstack[2+0-:1];
    led_output0[6+0+1+0-:1] = leftstack[3+0-:1];
    led_output0[8+0+1+0-:1] = leftstack[4+0-:1];
    led_output0[10+0+1+0-:1] = leftstack[5+0-:1];
    led_output0[12+0+1+0-:1] = leftstack[6+0-:1];
    led_output0[14+0+1+0-:1] = leftstack[7+0-:1];
    led_output0[16+0+1+0-:1] = leftstack[8+0-:1];
    led_output0[18+0+1+0-:1] = leftstack[9+0-:1];
    led_output1[0+0+1+0-:1] = middlestack[0+0-:1];
    led_output1[2+0+1+0-:1] = middlestack[1+0-:1];
    led_output1[4+0+1+0-:1] = middlestack[2+0-:1];
    led_output1[6+0+1+0-:1] = middlestack[3+0-:1];
    led_output1[8+0+1+0-:1] = middlestack[4+0-:1];
    led_output1[10+0+1+0-:1] = middlestack[5+0-:1];
    led_output1[12+0+1+0-:1] = middlestack[6+0-:1];
    led_output1[14+0+1+0-:1] = middlestack[7+0-:1];
    led_output1[16+0+1+0-:1] = middlestack[8+0-:1];
    led_output1[18+0+1+0-:1] = middlestack[9+0-:1];
    led_output2[0+0+1+0-:1] = rightstack[0+0-:1];
    led_output2[2+0+1+0-:1] = rightstack[1+0-:1];
    led_output2[4+0+1+0-:1] = rightstack[2+0-:1];
    led_output2[6+0+1+0-:1] = rightstack[3+0-:1];
    led_output2[8+0+1+0-:1] = rightstack[4+0-:1];
    led_output2[10+0+1+0-:1] = rightstack[5+0-:1];
    led_output2[12+0+1+0-:1] = rightstack[6+0-:1];
    led_output2[14+0+1+0-:1] = rightstack[7+0-:1];
    led_output2[16+0+1+0-:1] = rightstack[8+0-:1];
    led_output2[18+0+1+0-:1] = rightstack[9+0-:1];
  end
endmodule
