/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module lfsr_rand_23 (
    input clk,
    input rst,
    input enable,
    output reg [9:0] out
  );
  
  
  
  reg mid43;
  
  reg mid32;
  
  reg [3:0] newnum;
  
  reg [3:0] M_curr_num_d, M_curr_num_q = 4'hf;
  
  always @* begin
    M_curr_num_d = M_curr_num_q;
    
    
    case (enable)
      1'h0: begin
        mid43 = M_curr_num_q[3+0-:1] ^ M_curr_num_q[2+0-:1];
        mid32 = mid43 ^ M_curr_num_q[1+0-:1];
        newnum = M_curr_num_q >> 1'h1 + mid32;
        if (newnum < 3'h4) begin
          out = 10'h3ff;
        end else begin
          if (newnum < 3'h7) begin
            out = 10'h1ff;
          end else begin
            if (newnum < 4'ha) begin
              out = 10'h0ff;
            end else begin
              if (newnum < 4'hd) begin
                out = 10'h07f;
              end else begin
                out = 10'h03f;
              end
            end
          end
        end
        M_curr_num_d = newnum;
      end
      1'h1: begin
        mid43 = 1'h0;
        mid32 = 1'h0;
        newnum = M_curr_num_q;
        if (newnum < 3'h4) begin
          out = 10'h3ff;
        end else begin
          if (newnum < 3'h7) begin
            out = 10'h1ff;
          end else begin
            if (newnum < 4'ha) begin
              out = 10'h0ff;
            end else begin
              if (newnum < 4'hd) begin
                out = 10'h07f;
              end else begin
                out = 10'h03f;
              end
            end
          end
        end
        M_curr_num_d = newnum;
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_curr_num_q <= 4'hf;
    end else begin
      M_curr_num_q <= M_curr_num_d;
    end
  end
  
endmodule
